version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stocktraderdb
  transaction:
    image: benhillier/realstocktrader
    ports:
      - 0.0.0.0:8080:8080/tcp