version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: benhillier/stock-trader:2
    deploy:
      replicas: 6 
      resources:
        limits:
          cpus: "0.5"
          memory: 800M
      restart_policy:
        condition: on-failure
    ports:
      - 0.0.0.0:8080:8080/tcp
    networks:
      - webnet
networks:
  webnet:
